### ISSUE TITLE
{     "error": "HTTP 404 Not Found, {\"message\": \"Unknown Channel\", \"code\": 10003}" }

### ISSUE THREAD

**Issue by magang0425** [missuo/discord-image#1]
CHANNEL_ID 是正确的，但是提示：Unknown Channel\

**Comment by missuo** [comment]
> CHANNEL_ID 是正确的，但是提示：Unknown Channel\

可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？

**Comment by magang0425** [comment]
> > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> 
> 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？

bot在成员列表中，采用的docker-compose方式。

**Comment by missuo** [comment]
> > > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> > 
> > 
> > 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？
> 
> bot在成员列表中，采用的docker-compose方式。

请问你是如何获取 Channel ID 的？

**Comment by magang0425** [comment]
> > > > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> > > 
> > > 
> > > 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？
> > 
> > 
> > bot在成员列表中，采用的docker-compose方式。
> 
> 请问你是如何获取 Channel ID 的？

选中channel，右键：点击 复制
<img width="167" alt="image" src="https://github.com/missuo/discord-image/assets/3964343/7d7fe9a8-2e49-4b99-b1fb-9a0f38e8c961">

**Comment by missuo** [comment]
> > > > > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> > > > 
> > > > 
> > > > 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？
> > > 
> > > 
> > > bot在成员列表中，采用的docker-compose方式。
> > 
> > 
> > 请问你是如何获取 Channel ID 的？
> 
> 选中channel，右键：点击 复制 <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/3964343/321555891-7d7fe9a8-2e49-4b99-b1fb-9a0f38e8c961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQ0OTAsIm5iZiI6MTcxMjgyNDE5MCwicGF0aCI6Ii8zOTY0MzQzLzMyMTU1NTg5MS03ZDdmZTlhOC0yZTQ5LTRiOTktYjFmYi05YTBmMzhlOGM5NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDgyOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI2M2IxOTE1ZmYzNGFlNjY1ZGNlNDJhZjcxOWY5MzQ1Njg4NmM0NmU2NzcyMWU5MGQ2NjZjZjU4OTQ0NjllMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PBDuCe6NLjhuUWFgfgQ9YBFCv8sPu815Bf0YwDo6n5I">

生成授权 Bot 的链接的时候，勾选了哪些权限？

**Comment by magang0425** [comment]
> > > > > > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> > > > > 
> > > > > 
> > > > > 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？
> > > > 
> > > > 
> > > > bot在成员列表中，采用的docker-compose方式。
> > > 
> > > 
> > > 请问你是如何获取 Channel ID 的？
> > 
> > 
> > 选中channel，右键：点击 复制 <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/3964343/321555891-7d7fe9a8-2e49-4b99-b1fb-9a0f38e8c961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQ0OTAsIm5iZiI6MTcxMjgyNDE5MCwicGF0aCI6Ii8zOTY0MzQzLzMyMTU1NTg5MS03ZDdmZTlhOC0yZTQ5LTRiOTktYjFmYi05YTBmMzhlOGM5NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDgyOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI2M2IxOTE1ZmYzNGFlNjY1ZGNlNDJhZjcxOWY5MzQ1Njg4NmM0NmU2NzcyMWU5MGQ2NjZjZjU4OTQ0NjllMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PBDuCe6NLjhuUWFgfgQ9YBFCv8sPu815Bf0YwDo6n5I">
> 
> 生成授权 Bot 的链接的时候，勾选了哪些权限？

管理员权限  
<img width="506" alt="image" src="https://github.com/missuo/discord-image/assets/3964343/d6d68cd2-ba87-43c5-b207-b5c93bd9190c">

**Comment by missuo** [comment]
> > > > > > > CHANNEL_ID 是正确的，但是提示：Unknown Channel\
> > > > > > 
> > > > > > 
> > > > > > 可能是因为你的 Bot 不在 Channel 里面吧？你可以检测一下，`general` 的成员列表里面，有没有你的 Bot？
> > > > > 
> > > > > 
> > > > > bot在成员列表中，采用的docker-compose方式。
> > > > 
> > > > 
> > > > 请问你是如何获取 Channel ID 的？
> > > 
> > > 
> > > 选中channel，右键：点击 复制 <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/3964343/321555891-7d7fe9a8-2e49-4b99-b1fb-9a0f38e8c961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQ0OTAsIm5iZiI6MTcxMjgyNDE5MCwicGF0aCI6Ii8zOTY0MzQzLzMyMTU1NTg5MS03ZDdmZTlhOC0yZTQ5LTRiOTktYjFmYi05YTBmMzhlOGM5NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDgyOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI2M2IxOTE1ZmYzNGFlNjY1ZGNlNDJhZjcxOWY5MzQ1Njg4NmM0NmU2NzcyMWU5MGQ2NjZjZjU4OTQ0NjllMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PBDuCe6NLjhuUWFgfgQ9YBFCv8sPu815Bf0YwDo6n5I">
> > 
> > 
> > 生成授权 Bot 的链接的时候，勾选了哪些权限？
> 
> 管理员权限 <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/3964343/321558918-d6d68cd2-ba87-43c5-b207-b5c93bd9190c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQ5MDAsIm5iZiI6MTcxMjgyNDYwMCwicGF0aCI6Ii8zOTY0MzQzLzMyMTU1ODkxOC1kNmQ2OGNkMi1iYTg3LTQzYzUtYjIwNy1iNWM5M2JkOTE5MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDgzNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg3NzcyODc4MTlhYWJmZjJhM2ZiOGRmMTQ0YmMxZjhhMjExMGI3OGVjOGRkNjIwYWM0MDU1YTU0YTM4NmIxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.goJuxwtguORJHaViv0oV62JErS8AsNZcVolNnY2xkio">

不是这个！！

**Comment by missuo** [comment]
<img width="1861" alt="image" src="https://github.com/missuo/discord-image/assets/55200481/932960e5-f495-49d4-8265-d2374c75ef71">

**Comment by magang0425** [comment]
![image](https://github.com/missuo/discord-image/assets/3964343/9842ee34-775b-4c44-bc0b-6a91f3a0cf9d)
![image](https://github.com/missuo/discord-image/assets/3964343/735efb33-b29d-49e6-bf4a-4a45d9a7fba0)
我新建了一个bot，重新走了一遍，还是提示：HTTP 404 Not Found, {"message": "Unknown Channel", "code": 10003}
