### ISSUE TITLE
希望增加粘贴图片上传功能

### ISSUE THREAD

**Issue by tangdino** [missuo/discord-image#4]
希望增加截图直接粘贴上传功能

**Comment by missuo** [comment]
The web page is just a demo. In fact, you can use upload tools, such as picgo, upic, etc.

**Comment by tangdino222** [comment]
> The web page is just a demo. In fact, you can use upload tools, such as picgo, upic, etc.

你好 如果使用picgo上传 Picgo那边需要用到什么插件怎么设置？
